### ISSUE TITLE
Constant "A new version is available" message

### ISSUE THREAD

**Issue by cyberofficial** [tunnels-is/nicelandvpn-desktop#1]
**Describe the bug**
Application shows there's an update when using the latest version.

**To Reproduce**
1. Download build from website
2. Launch application and see there is an update message

**Expected behavior**
After updating, it should remove there is an update

**Screenshots**
<img width="779" alt="opera_cFzEOcQwl6" src="https://github.com/tunnels-is/nicelandvpn-desktop/assets/19499442/b8bbfce4-fd99-4a0a-903d-925449460d95">

**Niceland VPN version**
Windows Build [v1.1.0](https://github.com/tunnels-is/nicelandvpn-desktop/releases/tag/v1.1.0)

**Additional context**
Uninstalling and reinstalling does not fix the issue.

**Comment by zveinn** [comment]
The version variable is being compared to an old version storage object. We will fix this during the next update.

Thank you!
