### ISSUE TITLE
Endless "You are connecting to" Dialogs

### ISSUE THREAD

**Issue by cyberofficial** [tunnels-is/nicelandvpn-desktop#2]
**Describe the bug**
You can spam click a connection and shows "You are connecting to" endlessly, after a while it can crash the application.

**To Reproduce**
1. Open applcation
2. Spam click a connection

**Expected behavior**
Click on a connection, show dialog once, then connect.

**Video**

https://github.com/tunnels-is/nicelandvpn-desktop/assets/19499442/68c1c48d-5194-495d-9a40-0700a9af9205

**Niceland VPN version**
[v1.1.0](https://github.com/tunnels-is/nicelandvpn-desktop/releases/tag/v1.1.0)

**Additional context**
Spam clicking for like a minute straight causes the app to freeze (might be a race condition?)

**Comment by zveinn** [comment]
Thank you for the submission!

We will fix this during the next update.
