### ISSUE TITLE
When using search bar on windows client it broke my account

### ISSUE THREAD

**Issue by cyberofficial** [tunnels-is/nicelandvpn-desktop#20]
**Describe the bug**
When using search bar on windows client program bricks and you can not login

**To Reproduce**
1. Log in
2. click search
3. program breaks, asks to reload
4. doesnt allow login anymore, still break
5. try on new pc account unable to login.
6. Creating a new account works

**Expected behavior**
Reset and Allow login

**Screenshots**
![opera_wgpytEjUuf](https://github.com/tunnels-is/nicelandvpn-desktop/assets/19499442/b2932a6b-3b66-4822-bc70-a9a10cfeb323)

**Niceland VPN version**
[v1.1.4](https://github.com/tunnels-is/nicelandvpn-desktop/tree/v1.1.4)

**Additional context**
Tried to clear temp folder, reinstalled, erase 'files' in the program folder, delete app data files

**Comment by zveinn** [comment]
Turns out the search bar did not break the account. 

The crashes were caused by a Private VPN that was missing some fields. It will be solved during the next update
