### ISSUE TITLE
New version available message

### ISSUE THREAD

**Issue by cyberofficial** [tunnels-is/nicelandvpn-desktop#40]
**Describe the bug**
No new version available [also downloaded the exe from the website just to make sure, and still shows.

**To Reproduce**
1. Log in to the app
2. Observe new version available with "New version message

**Expected behavior**
Just show "No active subscription or no message"

**Screenshots**
![opera_PmIvko8C94](https://github.com/tunnels-is/nicelandvpn-desktop/assets/19499442/7d97b738-518b-41a9-8dd1-5a953dc3a995)

**Niceland VPN version**
[v1.1.4](https://github.com/tunnels-is/nicelandvpn-desktop/releases/tag/v1.1.4)

**Comment by zveinn** [comment]
This should be fixed soon! thank you for reporting
